# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_time__',
    '__build_status__'
]

__version__ = '0.0.0.dev5+gb9f8a32c'
__version_short__ = '0.0.0'
__version_long__ = '0.0.0'
__version_post__ = '5'
__version_commit__ = 'b9f8a32c'
__version_date__ = '2018-12-29 01:40:08 -0500'
__version_dirty__ = True
__build_date__ = '2018-12-29'
__build_time__ = '15:09:09.005338'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
