
# AUTOMATICALLY GENERATED BY 'RELIC':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_short__',
    '__version_long__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = 'c1197987'
__version_short__ = 'c1197987'
__version_long__ = 'c1197987-dirty'
__version_post__ = '-1'
__version_commit__ = 'c1197987'
__version_date__ = '2017-05-07 22:47:26 -0400'
__version_dirty__ = True
__build_date__ = '2017-05-09'
__build_time__ = '00:34:27.477164'
__build_status__ = 'release' if not int(__version_post__) > 0 \
    and not __version_dirty__ \
    else 'development'
